### ISSUE TITLE
Integrating into an existing app

### ISSUE THREAD

**Issue by MaxLap** [testdouble/good-migrations#25]
Hello, I'm looking to introduce this gem to a project I have at work. That project has been ongoing for 10 years, you can imagine how many older migrations we have that can be using code in a way that this gem blocks.

My issue is I don't have any desire to edit the many hundreds existing migrations. So what I think would be ideal for my need, is if I could setup a date, and migrations before that date can load code, while those after it cannot.

A way I thought would be to look at the `caller` when the loading happens and if a migration file is in that stack, then allow the loading.

I would be open to work on a PR for this, but since you currently have no configuration system, I'm not sure where I could do such configuration.

A configuration system would be useful for other things. For example, I think it would be great if I could write the error message myself, so that I can provide information specific for my application, such as helpers that people can use for some simple actions.

**Comment by searls** [comment]
Yes, I think this is a very interesting idea and something that makes sense as an option. I imagine it'll be as complicated an implementation as the rest of the gem combined (especially if it supports both zeitwerk and non-zeitwerk loaders), so I think having really good testing around it would be important if you do submit a PR

**Comment by MaxLap** [comment]
Alright, great.

Could you take care of adding a configuration system? This is your gem and there are many ways of doing this. As a simple first configuration, you make the error message configurable.

Here's how I'm thinking I would do the date part:
* 2 configurations:
  * `:allow_migrations_before_date` and `allow_loading_proc`
* The logic of checking the date would be in the default value of `allow_loading_proc`, which also receive the path being loaded.
* Devs could change the rule by changing the block's config. This could allow just about any customization that can be needed.

What are your thoughts on this?

**Comment by searls** [comment]
I think this makes sense. `allow` is an ambiguous word here, and `ignore` might be better. How about:

* `permit_autoloading_before_date`
* `permit_autoloading_for { |path| }` (since whether it's a block, proc argument, or lambda is inconsequential)

Personally, unless you have a compelling use case in mind for when the block configuration would be warranted, I would rather not add it.

One other consideration. I think the most reasonable "date" value to set this to would be the autogenerated timestamp string in the migration filename, so please make sure it works if the user passes that exact value as a string, or a date, or a time, and that it's just compared appropriately to the path.

**Comment by MaxLap** [comment]
That config name sounds good to me.

Ideas of use-cases for the block:
* If I remember well, much older version of rails made migrations with just sequential numbers instead of timestamps. This little extra complexity for the handling of the date might not be worth it, but if someone needs it, it can be done.
* There were requests for blocking other paths, such a lib/. 
* Any one desiring to have whatever rule make sense to them would be able to do so.

But maybe that could be moved to a future step, to first flesh out the main functionality.

**Comment by searls** [comment]
Ok, I'm convinced. Let's do both config options with clear documentation explaining that the date option is the default value for `permit_autoloading_for_path`. Signature for that option should probably be `permit_autoloading_for_path(callable = nil, &blk)` and default to callable, then raise if neither callable or blk is set
