### ISSUE TITLE
Included Gemfile.lock triggers vulnerability scanners

### ISSUE THREAD

**Issue by aburgel** [testdouble/good-migrations#39]
We have a Rails app using good migrations, it's published to an image registry that has a vulnerability scanner running (AWS Inspector). Because this gem includes a Gemfile.lock that is pretty out of date, the scanner flags our image with a bunch of critical issues.

Any chance you can publish a new version of the gem that excludes the Gemfile.lock? (maybe the Gemfile too? I'm not sure if that triggers the scanner.)

**Comment by rosston** [comment]
I've published v0.3.0, which excludes the Gemfile and Gemfile.lock. However, note that I bumped the minimum Ruby version to 3.1 in that release (for unrelated reasons, to get CI working again).
